import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

import ProfilItem from '../components/profilio/ProfilItem'
import ButtonItem from '../components/ButtonItem'

const DUMMY_IMAGE = [
  {
    title: 'Ferst Second',
    image: '/faces.jpg',
  },
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create -NiceNext- App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico.jpg" />
      </Head>

      <main className={styles.main}>
  
  <section className={styles.code}>
          <ProfilItem meetups={DUMMY_IMAGE} />
        </section>
    
  <p>
          {''}
          Hey guys , I am RycharDson , i'm like this course. Thanks for
          enrolling in this course!
        </p>

        <h1 className={styles.title}>
          Go <Link href="/posts/first-post">second page</Link>
        </h1>
        <ButtonItem meetups={DUMMY_IMAGE} />


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
